### ISSUE TITLE
Rails v Sinatra

### ISSUE THREAD

**Issue by mattficke** [ga-dc/rails_intro_hw#21]
Similarities between Rails and Sinatra:
-Both use the Active Record ORM to handle database actions
-Both use the MVC pattern, with an object model linked to the database structure, controllers to handle actions based on routes, and views to display data passed to it as html.

Differences:
-Rails automatically reloads the application with each browser request, removing the need for something like Sinatra Reloader
-Rails includes a number of Generator functions that automatically create commonly used files when beginning a project or during other common tasks such as creating controllers or database migrations.

**Comment by RobertAKARobin** [comment]
Hi, Matt!

**Comment by mattficke** [comment]
👋
Doing some spring cleaning of my open issues. How's everything? Heard you're moving soon.
